# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BooksMenu.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BookView(object):
    def setupUi(self, BookView):
        BookView.setObjectName("BookView")
        BookView.resize(1080, 800)
        BookView.setMinimumSize(QtCore.QSize(1080, 800))
        BookView.setMaximumSize(QtCore.QSize(1080, 800))
        self.centralwidget = QtWidgets.QWidget(BookView)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1080, 800))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1081, 781))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(0, 212, 1081, 341))
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.edition_label = QtWidgets.QLabel(self.page)
        self.edition_label.setGeometry(QtCore.QRect(270, 370, 540, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.edition_label.setFont(font)
        self.edition_label.setAlignment(QtCore.Qt.AlignCenter)
        self.edition_label.setObjectName("edition_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 240, 1081, 124))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(80)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(80)
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.start_b = QtWidgets.QPushButton(self.page)
        self.start_b.setGeometry(QtCore.QRect(270, 420, 540, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setItalic(True)
        self.start_b.setFont(font)
        self.start_b.setObjectName("start_b")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.books = QtWidgets.QTableWidget(self.page_2)
        self.books.setEnabled(True)
        self.books.setGeometry(QtCore.QRect(10, 150, 1060, 500))
        self.books.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.books.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.books.setDragEnabled(True)
        self.books.setObjectName("books")
        self.books.setColumnCount(5)
        self.books.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.books.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.books.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.books.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.books.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.books.setHorizontalHeaderItem(4, item)
        self.books.horizontalHeader().setCascadingSectionResizes(False)
        self.books.horizontalHeader().setDefaultSectionSize(211)
        self.books.verticalHeader().setCascadingSectionResizes(False)
        self.search = QtWidgets.QLineEdit(self.page_2)
        self.search.setGeometry(QtCore.QRect(40, 105, 600, 20))
        self.search.setObjectName("search")
        self.loopa = QtWidgets.QPushButton(self.page_2)
        self.loopa.setGeometry(QtCore.QRect(10, 100, 30, 30))
        self.loopa.setText("")
        self.loopa.setObjectName("loopa")
        self.titles_b = QtWidgets.QPushButton(self.page_2)
        self.titles_b.setGeometry(QtCore.QRect(660, 100, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.titles_b.setFont(font)
        self.titles_b.setObjectName("titles_b")
        self.authors_b = QtWidgets.QPushButton(self.page_2)
        self.authors_b.setGeometry(QtCore.QRect(800, 100, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.authors_b.setFont(font)
        self.authors_b.setObjectName("authors_b")
        self.genres_b = QtWidgets.QPushButton(self.page_2)
        self.genres_b.setGeometry(QtCore.QRect(940, 100, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.genres_b.setFont(font)
        self.genres_b.setObjectName("genres_b")
        self.check_b = QtWidgets.QPushButton(self.page_2)
        self.check_b.setGeometry(QtCore.QRect(180, 680, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.check_b.setFont(font)
        self.check_b.setObjectName("check_b")
        self.back_b = QtWidgets.QPushButton(self.page_2)
        self.back_b.setGeometry(QtCore.QRect(570, 680, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.back_b.setFont(font)
        self.back_b.setObjectName("back_b")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(50, 80, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(182, 182, 182);")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 271, 71))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(150, 10, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.back_b_2 = QtWidgets.QPushButton(self.page_3)
        self.back_b_2.setGeometry(QtCore.QRect(570, 680, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.back_b_2.setFont(font)
        self.back_b_2.setObjectName("back_b_2")
        self.buy_book_b = QtWidgets.QPushButton(self.page_3)
        self.buy_book_b.setEnabled(False)
        self.buy_book_b.setGeometry(QtCore.QRect(180, 680, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.buy_book_b.setFont(font)
        self.buy_book_b.setObjectName("buy_book_b")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(180, 745, 330, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(100, 80, 881, 411))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spacer_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.spacer_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spacer_1.setText("")
        self.spacer_1.setObjectName("spacer_1")
        self.horizontalLayout_2.addWidget(self.spacer_1)
        self.image_info = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.image_info.setText("")
        self.image_info.setObjectName("image_info")
        self.horizontalLayout_2.addWidget(self.image_info)
        self.spacer_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.spacer_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spacer_2.setText("")
        self.spacer_2.setObjectName("spacer_2")
        self.horizontalLayout_2.addWidget(self.spacer_2)
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 271, 71))
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(150, 10, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(0, 520, 1081, 151))
        self.label_15.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.year_info = QtWidgets.QLabel(self.page_3)
        self.year_info.setGeometry(QtCore.QRect(200, 640, 831, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.year_info.setFont(font)
        self.year_info.setText("")
        self.year_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.year_info.setObjectName("year_info")
        self.info_label_4 = QtWidgets.QLabel(self.page_3)
        self.info_label_4.setGeometry(QtCore.QRect(30, 640, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.info_label_4.setFont(font)
        self.info_label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_label_4.setObjectName("info_label_4")
        self.author_info = QtWidgets.QLabel(self.page_3)
        self.author_info.setGeometry(QtCore.QRect(200, 560, 831, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.author_info.setFont(font)
        self.author_info.setText("")
        self.author_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.author_info.setObjectName("author_info")
        self.info_label = QtWidgets.QLabel(self.page_3)
        self.info_label.setGeometry(QtCore.QRect(30, 520, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.info_label.setFont(font)
        self.info_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_label.setObjectName("info_label")
        self.info_label_3 = QtWidgets.QLabel(self.page_3)
        self.info_label_3.setGeometry(QtCore.QRect(30, 600, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.info_label_3.setFont(font)
        self.info_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_label_3.setObjectName("info_label_3")
        self.title_info = QtWidgets.QLabel(self.page_3)
        self.title_info.setGeometry(QtCore.QRect(200, 520, 831, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.title_info.setFont(font)
        self.title_info.setText("")
        self.title_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_info.setObjectName("title_info")
        self.info_label_2 = QtWidgets.QLabel(self.page_3)
        self.info_label_2.setGeometry(QtCore.QRect(30, 560, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.info_label_2.setFont(font)
        self.info_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_label_2.setObjectName("info_label_2")
        self.genre_info = QtWidgets.QLabel(self.page_3)
        self.genre_info.setGeometry(QtCore.QRect(200, 600, 831, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        self.genre_info.setFont(font)
        self.genre_info.setText("")
        self.genre_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.genre_info.setObjectName("genre_info")
        self.image_button = QtWidgets.QPushButton(self.page_3)
        self.image_button.setGeometry(QtCore.QRect(490, 40, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.image_button.setFont(font)
        self.image_button.setObjectName("image_button")
        self.stackedWidget.addWidget(self.page_3)
        BookView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BookView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")
        BookView.setMenuBar(self.menubar)

        self.retranslateUi(BookView)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(BookView)

    def retranslateUi(self, BookView):
        _translate = QtCore.QCoreApplication.translate
        BookView.setWindowTitle(_translate("BookView", "Book-Shelf (V-Like-Engined) v.1"))
        self.edition_label.setText(_translate("BookView", "The Only Edition (v.1), V-Like-Engined, 2019"))
        self.label_11.setText(_translate("BookView", "Book -"))
        self.label_12.setText(_translate("BookView", "Shelf"))
        self.start_b.setText(_translate("BookView", "Take a Book Look"))
        self.books.setSortingEnabled(False)
        item = self.books.horizontalHeaderItem(0)
        item.setText(_translate("BookView", "id"))
        item = self.books.horizontalHeaderItem(1)
        item.setText(_translate("BookView", "Title"))
        item = self.books.horizontalHeaderItem(2)
        item.setText(_translate("BookView", "Author"))
        item = self.books.horizontalHeaderItem(3)
        item.setText(_translate("BookView", "Genre"))
        item = self.books.horizontalHeaderItem(4)
        item.setText(_translate("BookView", "Year"))
        self.titles_b.setText(_translate("BookView", "In Titles"))
        self.authors_b.setText(_translate("BookView", "In Authors"))
        self.genres_b.setText(_translate("BookView", "In Genres"))
        self.check_b.setText(_translate("BookView", "Check Selected Book"))
        self.back_b.setText(_translate("BookView", "Back to Menu"))
        self.label_4.setText(_translate("BookView", "Search:"))
        self.label_3.setText(_translate("BookView", "Shelf"))
        self.label_13.setText(_translate("BookView", "Book -"))
        self.back_b_2.setText(_translate("BookView", "Back to Menu"))
        self.buy_book_b.setText(_translate("BookView", "Buy a book"))
        self.label_9.setText(_translate("BookView", "Not supported in your country, sorry"))
        self.label_7.setText(_translate("BookView", "Shelf"))
        self.label_8.setText(_translate("BookView", "Book -"))
        self.info_label_4.setText(_translate("BookView", "Year:"))
        self.info_label.setText(_translate("BookView", "Title:"))
        self.info_label_3.setText(_translate("BookView", "Genre:"))
        self.info_label_2.setText(_translate("BookView", "Author:"))
        self.image_button.setText(_translate("BookView", "Image..."))
